-- SQLite
CREATE TABLE header(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
logo BLOB NOT NULL,
nom VARCHAR(255) NOT NULL,
slogan VARCHAR(255) NOT NULL
);

CREATE TABLE domaine_accueil(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
icon VARCHAR(255) NOT NULL,
nom VARCHAR(255) NOT NULL,
description VARCHAR(1000) NOT NULL
);

CREATE TABLE equipe_propos(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
icon VARCHAR(255) NOT NULL,
nom VARCHAR(255) NOT NULL,
description VARCHAR(1000) NOT NULL
);

CREATE TABLE services_service(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
nom VARCHAR(255) NOT NULL,
description VARCHAR(1000) NOT NULL,
criteres_services JSON NOT NULL,
libelleImage BLOB NOT NULL
);

CREATE TABLE realisation_realisation(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
nom VARCHAR(255) NOT NULL,
description VARCHAR(1000) NOT NULL,
lien_button VARCHAR(500) NOT NULL,
criteres_services JSON NOT NULL,
libelleImage BLOB NOT NULL
);

CREATE TABLE membre_notreequipe(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
libelleImage BLOB NOT NULL,
nom VARCHAR(255) NOT NULL,
role VARCHAR(255) NOT NULL
);

CREATE TABLE services_footer(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
criteres VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
telephone INT(9) NOT NULL,
lienreseauxsociaux JSON NOT NULL
);
